name: top_dash_ui
description: UI Toolkit for Top Dash.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
