name: top_dash_ui
description: UI Toolkit for Top Dash.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0-417.1.beta <4.0.0"
  flutter: 3.10.0-1.1.pre

dependencies:
  equatable: ^2.0.5
  flame:
    git:
      url: https://github.com/willhlas/flame
      path: packages/flame
      ref: main
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.1
  flutter_svg: ^2.0.5
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  very_good_analysis: ^4.0.0

flutter:
  shaders:
    - shaders/foil.frag

  assets:
    - assets/images/
    - assets/images/suits/onboarding/
    - assets/images/suits/card/
    - assets/images/card_frames/

flutter_gen:
  line_length: 80
  assets:
    outputs:
      package_parameter_enabled: true

  integrations:
    flutter_svg: true
