name: connection_repository
description: Repository to manage the connection state
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  api_client:
    path: ../api_client
  equatable: ^2.0.5
  game_domain:
    path: ../../api/packages/game_domain
  web_socket_client: ^0.1.0-dev.3

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
