import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:top_dash/match_making/match_making.dart';
import 'package:uuid/uuid.dart';

class MatchMakingPage extends StatelessWidget {
  const MatchMakingPage({super.key});

  factory MatchMakingPage.routeBuilder(_, __) {
    return const MatchMakingPage(key: Key('match_making'));
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) {
        final matchMaker = context.read<MatchMaker>();
        // TODO(erickzanardo): using this to test the match making for now,
        // this id should be the id of the ticket generated by the drafting
        // phase.
        final id = const Uuid().v4();
        return MatchMakingBloc(
          matchMaker: matchMaker,
          playerId: id,
        )..add(
            const MatchRequested(),
          );
      },
      child: const MatchMakingView(),
    );
  }
}
