name: gallery
description: Gallery project to showcase app_ui
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  top_dash_ui:
    path: ../
  dashbook: ^0.1.11
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
