name: match_repository
description: Access to Match datasource
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cards_repository:
    path: ../cards_repository
  db_client:
    path: ../db_client
  equatable: ^2.0.5
  game_domain:
    path: ../game_domain
  image_model_repository:
    path: ../image_model_repository
  json_annotation: ^4.8.0
  language_model_repository:
    path: ../language_model_repository
  meta: ^1.9.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
