name: card_renderer
description: Renders a card based on its metadata and illustration
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  game_domain:
    path: ../game_domain
  http: ^0.13.5
  image: ^4.0.15

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
