name: api_encryption_middleware

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "api/packages/encryption_middleware/**"
      - ".github/workflows/api_encryption_middleware.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: stable
      working_directory: api/packages/encryption_middleware
